---
- name: Configure | taiga front | conf/main.example.json
  replace:
    dest: "{{ taiga_front_install_path }}/conf/main.example.json"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  notify: Reload Service | taiga-api
  with_items:
    - { regexp: "localhost:8000", replace: "{{ taiga_hostname }}:{{ taiga_port }}" }
  tags:
    - configuration
    - precise-configuration


- name: Configure | taiga-front | conf/main.json
  command: "cp {{ taiga_front_install_path }}/conf/main.example.json {{ taiga_front_install_path }}/conf/main.json"
