---
- name: Directory Exists | taiga | data
  file:
    state: directory
    path: "{{ taiga_data_install_path }}"
    owner: root
    group: wcadmin
    mode: 0755
  tags:
    - directory-structure

- name: Configure | taiga back | migrate schema
  shell: "cd {{ taiga_back_install_path }} && python3 manage.py migrate --noinput"

- name: Configure | taiga back | initial data
  shell: >
    chdir={{ taiga_back_install_path }}
    creates={{ taiga_data_install_path }}/{{ item }}
    python3 manage.py loaddata initial_{{ item }} && touch {{ taiga_data_install_path }}/{{ item }}
  with_items:
    - user
    - project_templates
    - role

- name: Configure | taiga back | sample data
  shell: >
    chdir={{ taiga_back_install_path }}
    creates={{ taiga_data_install_path }}/sample
    python3 manage.py loaddata sample_data && touch {{ taiga_data_install_path }}/sample
  when: taiga_import_sample_data

- name: Upload Config | nginx | taiga
  template:
    src: etc/nginx/sites-available/taiga.conf
    dest: /etc/nginx/sites-available/taiga.conf
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | nginx
  tags:
    - configuration
    - template-configuration
    - nginx

- name: Enable Config | nginx | taiga
  file:
    state: link
    src: /etc/nginx/sites-available/taiga.conf
    dest: /etc/nginx/sites-enabled/taiga
  notify: Reload Service | nginx
  tags:
    - configuration
    - enable-configuration
    - nginx
