---
- name: Configure | taiga front | conf/main.example.json
  lineinfile:
    state: present
    dest: "{{ taiga_front_install_path }}/conf/main.example.json"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  notify: Reload Service | taiga-api
  with_items:
    - { regexp: "^(.*)localhost:8000(.*)$", line: "\\1{{ taiga_hostname }}:{{ taiga_port }}\\2" }
  tags:
    - configuration
    - precise-configuration
    - networking
    - interface-binding

- name: Configure | taiga-front | conf/main.json
  command: "mv {{ taiga_front_install_path }}/conf/main.example.json {{ taiga_front_install_path }}/conf/main.json"
