---
- name: "Upload Config | taiga back | settings/local.py"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | taiga-api
  with_items:
    - "opt/taiga/back/settings/local.py"

- name: Configure | taiga back | settings/common.py
  replace:
    dest: "{{ taiga_back_install_path }}/settings/common.py"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  notify: Reload Service | taiga-api
  with_items:
    - { regexp: "localhost:8000", replace: "{{ taiga_hostname }}:{{ taiga_port }}" }
    - { regexp: "localhost:9001", replace: "{{ taiga_hostname }}:{{ taiga_port }}" }
    - { regexp: "^PUBLIC_REGISTER_ENABLED.*$", replace: "PUBLIC_REGISTER_ENABLED = {{ taiga_public_register_enabled }}" }
  tags:
    - configuration
    - precise-configuration
