---
- name: Install Packages | pip
  pip:
    executable: /usr/local/bin/pip3
    requirements: "{{ taiga_back_install_path }}/requirements.txt"

- name: "Upload Config | taiga | back settings"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  with_items:
    - "opt/taiga/back/settings/local.py"
    - "opt/taiga/back/settings/common.py"
