---
- name: "Directory Exists | taiga"
  file:
    state: directory
    path: "{{ taiga_install_root }}"
    owner: root
    group: wcadmin
    mode: 0775
  tags:
    - software-installation
    - directory-structure

- name: Install Packages | git
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.tag }}"
    accept_hostkey: yes
    update: yes
    force: yes
  with_items:
    - { repo: "{{ taiga_back_repo }}", dest: "{{ taiga_back_install_path }}", tag: "{{ taiga_back_version }}" }
    - { repo: "{{ taiga_front_repo }}", dest: "{{ taiga_front_install_path }}", tag: "{{ taiga_front_version }}" }
  tags:
    - software-installation
    - using-git
    - using-github
    - assumes-trust

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - libpq-dev
    - python3-setuptools
    - python3-dev

- name: Install Packages | easy_install
  easy_install:
    executable: /usr/bin/easy_install3
    name: pip
