---
- name: Directory Exists | taiga
  file:
    state: directory
    path: "{{ taiga_install_root }}"
    owner: root
    group: wcadmin
    mode: 0775
  tags:
    - software-installation
    - directory-structure

- name: Install Packages | git
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.tag }}"
    accept_hostkey: yes
    update: yes
    force: yes
  with_items:
    - { repo: "{{ taiga_back_repo }}", dest: "{{ taiga_back_install_path }}", tag: "{{ taiga_back_version }}" }
    - { repo: "{{ taiga_front_repo }}", dest: "{{ taiga_front_install_path }}", tag: "{{ taiga_front_version }}" }
  tags:
    - software-installation
    - using-git
    - using-github
    - assumes-trust

- name: Use a newer version of django-transactional-cleanup
  replace:
    dest: "{{ taiga_back_install_path }}/requirements.txt"
    regexp: django-transactional-cleanup==0.1.12
    replace: django-transactional-cleanup==0.1.13
  tags:
    - configuration
    - precise-configuration

- name: Install Packages | pip
  pip:
    #executable: /usr/bin/pip3
    #executable: /usr/local/bin/pip3
    requirements: "{{ taiga_back_install_path }}/requirements.txt"
  tags:
    - software-installation   
    - using-pip
