---
- name: "Directory Exists | taiga"
  file:
    state: directory
    path: "{{ taiga_install_root }}"
    owner: root
    group: wcadmin
    mode: 0775
  tags:
    - software-installation
    - directory-structure

- name: Install Packages | git
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.tag }}"
    accept_hostkey: yes
    update: yes
    force: yes
  with_items:
    - { repo: "{{ taiga_back_repo }}", dest: "{{ taiga_back_install_path }}", tag: "{{ taiga_back_version }}" }
    - { repo: "{{ taiga_front_repo }}", dest: "{{ taiga_front_install_path }}", tag: "{{ taiga_front_version }}" }
  tags:
    - software-installation
    - using-git
    - using-github
    - assumes-trust

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - libpq-dev
    - python3-setuptools
    - python3-dev

- name: Install Packages | easy_install
  easy_install:
    executable: /usr/bin/easy_install3
    name: pip


# taiga/front


- name: Install Packages | npm | package.json
  shell: "cd {{ taiga_front_install_path }} && npm install"
  # Fails to install certain packages when done through ansible module
  #npm:
  #  path: "{{ taiga_front_install_path }}"

- name: Install Packages | bower
  shell: "cd {{ taiga_front_install_path }} && bower install --allow-root"

- name: Compile | gulp
  shell: "gulp deploy --cwd {{ taiga_front_install_path }}"


# taiga/back


- name: Install Packages | pip
  pip:
    executable: /usr/bin/pip3
    requirements: "{{ taiga_back_install_path }}/requirements.txt"
