---
- name: "Upload Config | taiga | front settings"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  with_items:
    - "opt/taiga/front/conf/main.json"

- name: Install Packages | npm | package.json
  shell: "cd {{ taiga_front_install_path }} && npm install"
  # Fails to install certain packages when done through ansible module
  #npm:
  #  path: "{{ taiga_front_install_path }}"

- name: Install Packages | bower
  shell: "cd {{ taiga_front_install_path }} && bower install --allow-root"

- name: Compile | gulp
  shell: "gulp deploy --cwd {{ taiga_front_install_path }}"
