---
- name: "Directory Exists | {{ mci_log_root }}"
  file:
    state: directory
    path: "{{ mci_log_root }}"
    owner: "{{ mci_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - mci

- name: Upload Config | beaver | mci
  template:
    src: etc/beaver/conf.d/mci
    dest: /etc/beaver/conf.d/mci
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - mci
